runtime: nodejs22  # Specifies the runtime environment
env: standard      # Specifies the environment to use, standard or flexible

instance_class: F1  # Defines the class of GCP instance to use

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65  # Target CPU utilization percentage
  min_instances: 1              # Minimum number of instances
  max_instances: 5              # Maximum number of instances

# Environment variables that you want to set
env_variables:
  NODE_ENV: 'production'
  API_KEY: ${API_KEY}

# Handlers define rules to handle incoming routes
handlers:
  # Serve all traffic using the app
  - url: /.*
    script: auto
    secure: always

  # Static files configuration
  - url: /stylesheets
    static_dir: stylesheets

  # Redirect HTTP traffic to HTTPS
  - url: /.*
    redirect_http_response_code: 301
    script: auto
    secure: always

# Health checks configuration (optional)
health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
