runtime: nodejs22

env_variables:
  # These should match the variables from your .env file.
  PORT: "8080"
  THEME_VAPOR: "your_vapor_theme_url"
  THEME_SOLAR: "your_solar_theme_url"
  BOOTSTRAP_JS_URL: "your_bootstrap_js_url"
  BOOTSTRAP_CSS_URL: "your_bootstrap_css_url"
  POPPER_JS_URL: "your_popper_js_url"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /public
    static_dir: public

  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /.*
    script: auto

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  healthy_threshold: 2
  unhealthy_threshold: 10

liveness_check:
  path: "/health"
  initial_delay_sec: 30
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 5
  success_threshold: 1
